export const rooms = [
 {id:1,slug:'oceanfront-terrace',name:'Oceanfront Terrace',category:'Signature',price:310,guests:2,bed:'1 King bed',view:'Ocean view',size:42,image:'/images/pool.png',description:'Your own front-row seat to the sea. A generous king suite opens onto a private terrace, with soft linen, natural textures and the sound of waves just beyond.'},
 {id:2,slug:'coastal-king',name:'Coastal King',category:'Premium',price:290,guests:2,bed:'1 King bed',view:'Private balcony',size:34,image:'/images/room.png',description:'Wake slowly in a light-filled king room. Slide open the balcony doors, make a fresh coffee and let the sea breeze set the pace for the day.'},
 {id:3,slug:'garden-courtyard',name:'Garden Courtyard',category:'Classic',price:190,guests:2,bed:'1 Queen bed',view:'Garden courtyard',size:28,image:'/images/room.png',description:'A quiet retreat wrapped in greenery. This intimate queen room pairs relaxed comfort with a sheltered courtyard made for a good book.'},
 {id:4,slug:'ocean-breeze-twin',name:'Ocean Breeze Twin',category:'Classic',price:180,guests:2,bed:'2 Single beds',view:'Garden view',size:30,image:'/images/room.png',description:'Easy days, shared adventures. Our twin room offers two comfortable beds, thoughtful essentials and a peaceful outlook over the coastal garden.'}
];
export const experiences = [
 {slug:'surf-and-sea',title:'Catch the early. And the calm.',label:'Surf & sea',image:'/images/coast.png',text:'Take a morning dip, watch the surf or spend the afternoon with your feet in the sand. The shoreline is the best place to leave a busy week behind.',detail:'Bring a towel, reef-safe sunscreen and water. Ask our team about local conditions and surf lessons before heading out.'},
 {slug:'local-flavours',title:'Fresh ingredients. Coastal soul.',label:'Local flavours',image:'/images/pool.png',text:'Long lunches, fresh seasonal produce and a coffee worth getting up for. Discover independent cafés and relaxed coastal dining.',detail:'Our team can help with a short list of nearby cafés and dinner reservations. Opening hours and menus vary by season.'},
 {slug:'scenic-walks',title:'Hidden tracks. Big views.',label:'Scenic walks',image:'/images/coast.png',text:'Follow the coast at your own pace. Find quiet lookouts, salt-sprayed headlands and little places to stop along the way.',detail:'Choose a walk to suit your ability, check the weather and stay on marked paths. Comfortable shoes are recommended.'},
 {slug:'unwind',title:'Do less. Better.',label:'Unwind',image:'/images/pool.png',text:'A poolside afternoon. One more chapter. Absolutely nowhere to be. Sometimes the best plan is no plan at all.',detail:'Pool towels are available for guests. Enjoy the shared terrace and quiet corners of our garden throughout your stay.'}
];
export const articles = [
 {slug:'coastal-mornings',title:'Five little rituals for a coastal morning',date:'08 MAY 2026',image:'/images/coast.png',category:'Slow living',intro:'Leave room in your morning for something that does not need to be rushed.',sections:[['Meet the first light','Open the curtains before picking up your phone. Watch the light move across the sea, even if only for a minute.'],['Walk without a destination','A short stroll can be enough. Feel the air, notice the changing tide and find a place to pause.'],['Make breakfast a moment','Sit down with your coffee. Try something seasonal, share the table and let breakfast last a little longer.'],['Take a quiet swim','Check local swimming conditions with the team, or choose a gentle dip in the pool.'],['Leave the day open','Choose one thing you would love to do, then leave space around it. A holiday should have room to surprise you.']]},
 {slug:'long-lunch',title:'The art of a very long lunch',date:'03 MAY 2026',image:'/images/pool.png',category:'Food & drink',intro:'A table in the shade, good company and nowhere to hurry back to.',sections:[['Keep it seasonal','Seek out simple dishes made with local ingredients. Ask what is fresh and let that guide your order.'],['Ask a local','Our team loves sharing suggestions for relaxed cafés and restaurants. Tell us what you enjoy and we will help you find a good fit.'],['Stay for another story','The best part of lunch is often the conversation after the plates have been cleared. Leave time for it.']]},
 {slug:'lazy-sunday',title:'Your guide to a wonderfully lazy Sunday',date:'26 APR 2026',image:'/images/room.png',category:'Stay a while',intro:'Permission to put very little on the itinerary.',sections:[['Start in your own time','Sleep in, open a book and enjoy a slow coffee on the terrace.'],['Choose the simple things','A walk, a swim, an easy lunch. You do not need to fill every hour to have a memorable day.'],['Finish with the view','Find a comfortable spot before sunset. Watch the light soften and let tomorrow wait.']]}
];
export const money = (amount:number) => new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(amount);
